---
#Main YML to execute all roles and playbook
- hosts: local
  gather_facts: false
  user: root

  roles:
    - {role: 'common', tags: 'create'}

    - {role: 'terminate', tags: 'delete'}
    

- hosts: webservers
  gather_facts: false
  remote_user: ubuntu
  become: yes
  roles:
    - {role: 'ubuntu', tags: 'create'}
...