---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Pull default Docker image
  docker_image:
    name: ubuntu
    source: pull

- name: Chaning mode for docker file
  become: true
  command: chmod 777 /var/run/docker.sock


- name: Kubectl Installation
  shell: |
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    sudo chmod +x ./kubectl
    sudo mv ./kubectl /usr/local/bin/kubectl
    kubectl version --client


- name: Helm Installation
  shell: |
    sudo wget https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz
    sudo tar -zxvf helm-v3.1.1-linux-amd64.tar.gz
    sudo mv linux-amd64/helm /usr/local/bin/helm

- name: yq Installation
  shell: |
    sudo add-apt-repository -y ppa:rmescandon/yq
    sudo apt update
    sudo apt install yq -y

...

