---
- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
    #Creating a Key Pair for EC Instance
    - name: Create a new ec2 key pair
      ec2_key:
        name: ec2_keypair
        region: "{{ region }}"
      register: keypair

    #Creating and Launching EC2 instance
    - name: Create EC2 Instance
      ec2:
        image: ami-0d03e44a2333dea65
        wait: yes
        instance_type: t2.micro
        region: "{{ region }}"
        group_id: "{{ security_group.group_id }}"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        key_name: "{{ keypair.key.name  }}"
        count_tag:
          Name: jenkins
        exact_count: 1
...
